"""Chat and message repository.

This module carries two of the project's performance commitments, so the queries here
are written deliberately rather than generated by convenience:

* **Listing chats** is a keyset seek served by the partial index ``ix_chat_list``, with
  a target of 30 ms over ten thousand conversations (ADR-0007).
* **Opening a conversation** is a single indexed range scan over
  ``(chat_id, depth, id)`` selecting explicit columns — never ``SELECT *``, because the
  message body is the largest column and most of it is not needed to render a list.
  The tree is reassembled in Python, which for five thousand rows is a dictionary pass
  costing well under a millisecond, and the active path is walked from the leaf back to
  the root (ADR-0006).
"""

from __future__ import annotations

from collections.abc import Sequence
from typing import Any, cast

import msgspec
from sqlalchemy import CursorResult, Select, select, tuple_, update
from sqlalchemy.ext.asyncio import AsyncSession

from velox_ui.clock import now_ms
from velox_ui.db.models import Chat, Message
from velox_ui.ids import new_ulid

__all__ = ["ChatCursor", "ChatListPage", "ChatRepository", "ChatSummary", "MessageNode"]

# The ordering key of the chat list, in the order ix_chat_list declares it.
type ChatCursor = tuple[bool, int, str]


class ChatSummary(msgspec.Struct, frozen=True):
    """One row of the chat sidebar. Deliberately small: no message bodies."""

    id: str
    title: str
    pinned: bool
    archived: bool
    folder_id: str | None
    model_ref: str | None
    message_count: int
    updated_at: int


class ChatListPage(msgspec.Struct, frozen=True):
    """A page of chat summaries plus the cursor for the next one."""

    items: tuple[ChatSummary, ...]
    next_cursor: str | None


class MessageNode(msgspec.Struct, frozen=True):
    """A message on the active path, with enough context to render branch controls."""

    id: str
    parent_id: str | None
    role: str
    content: str
    reasoning: str | None
    status: str
    model_ref: str | None
    depth: int
    tokens_in: int | None
    tokens_out: int | None
    cost_micros: int | None
    timings: dict[str, Any] | None
    error: dict[str, Any] | None
    created_at: int
    sibling_index: int
    sibling_count: int


_SUMMARY_COLUMNS = (
    Chat.id,
    Chat.title,
    Chat.pinned,
    Chat.archived,
    Chat.folder_id,
    Chat.model_ref,
    Chat.message_count,
    Chat.updated_at,
)

_MESSAGE_COLUMNS = (
    Message.id,
    Message.parent_id,
    Message.role,
    Message.content,
    Message.reasoning,
    Message.status,
    Message.model_ref,
    Message.depth,
    Message.tokens_in,
    Message.tokens_out,
    Message.cost_micros,
    Message.timings,
    Message.error,
    Message.created_at,
)


class ChatRepository:
    """Reads and writes conversations.

    Args:
        session: The session to operate in.
    """

    __slots__ = ("_session",)

    def __init__(self, session: AsyncSession) -> None:
        """Bind the repository to a session."""
        self._session = session

    async def create(
        self,
        *,
        user_id: str,
        title: str,
        folder_id: str | None = None,
        model_ref: str | None = None,
    ) -> Chat:
        """Create an empty conversation."""
        moment = now_ms()
        chat = Chat(
            id=new_ulid(),
            user_id=user_id,
            folder_id=folder_id,
            title=title,
            active_leaf_id=None,
            model_ref=model_ref,
            pinned=False,
            archived=False,
            message_count=0,
            meta=None,
            created_at=moment,
            updated_at=moment,
            deleted_at=None,
        )
        self._session.add(chat)
        return chat

    async def get(self, chat_id: str, *, user_id: str) -> Chat | None:
        """Return a conversation owned by ``user_id``, or ``None``.

        Ownership is part of the query rather than a check afterwards, so a wrong id
        and someone else's id are indistinguishable to the caller.
        """
        stmt = select(Chat).where(
            Chat.id == chat_id, Chat.user_id == user_id, Chat.deleted_at.is_(None)
        )
        return (await self._session.execute(stmt)).scalar_one_or_none()

    def _list_statement(
        self, *, user_id: str, archived: bool, folder_id: str | None
    ) -> Select[Any]:
        """Build the base listing query, matching ``ix_chat_list`` column for column."""
        stmt = (
            select(*_SUMMARY_COLUMNS)
            .where(
                Chat.user_id == user_id,
                Chat.archived == archived,
                Chat.deleted_at.is_(None),
            )
            .order_by(Chat.pinned.desc(), Chat.updated_at.desc(), Chat.id.desc())
        )
        if folder_id is not None:
            stmt = stmt.where(Chat.folder_id == folder_id)
        return stmt

    async def list_page(
        self,
        *,
        user_id: str,
        limit: int,
        cursor: ChatCursor | None = None,
        archived: bool = False,
        folder_id: str | None = None,
    ) -> tuple[Sequence[ChatSummary], ChatCursor | None]:
        """Return one page of chat summaries.

        Args:
            user_id: Owner.
            limit: Page size, already clamped by the route.
            cursor: Ordering tuple of the last row of the previous page, or ``None``.
            archived: Which shelf to list.
            folder_id: Restrict to one folder.

        Returns:
            The page and the ordering tuple to pass back as the next cursor, or
            ``None`` when the list is exhausted.

        The cursor comparison is a row-value expression rather than an expanded chain
        of ``OR``s: every ordering column is descending, so one row-value comparison is
        both correct and the form the index can seek on directly.
        """
        stmt = self._list_statement(user_id=user_id, archived=archived, folder_id=folder_id)
        if cursor is not None:
            pinned, updated_at, chat_id = cursor
            stmt = stmt.where(
                tuple_(Chat.pinned, Chat.updated_at, Chat.id) < (pinned, updated_at, chat_id)
            )

        rows = (await self._session.execute(stmt.limit(limit + 1))).all()
        has_more = len(rows) > limit
        page = rows[:limit]
        items = tuple(
            ChatSummary(
                id=row.id,
                title=row.title,
                pinned=bool(row.pinned),
                archived=bool(row.archived),
                folder_id=row.folder_id,
                model_ref=row.model_ref,
                message_count=row.message_count,
                updated_at=row.updated_at,
            )
            for row in page
        )
        if not has_more or not page:
            return items, None
        last = page[-1]
        return items, (bool(last.pinned), int(last.updated_at), str(last.id))

    async def append_message(
        self,
        *,
        chat_id: str,
        parent_id: str | None,
        role: str,
        content: str = "",
        status: str = "complete",
        model_ref: str | None = None,
        message_id: str | None = None,
        depth: int | None = None,
    ) -> Message:
        """Insert a message node.

        Args:
            chat_id: Conversation the message belongs to.
            parent_id: Parent node, or ``None`` for the root turn.
            role: ``system``, ``user``, ``assistant`` or ``tool``.
            content: Body. Empty for an assistant message that is about to stream.
            status: ``complete``, ``streaming``, ``stopped`` or ``error``.
            model_ref: Which model served the message.
            message_id: Pre-generated id. The streaming path allocates the id before
                the row exists so it can be sent to the client immediately (ADR-0005).
            depth: Pre-computed depth. Looked up from the parent when omitted.

        Returns:
            The pending :class:`~velox_ui.db.models.Message`.
        """
        if depth is None:
            depth = 0 if parent_id is None else await self._depth_of(parent_id) + 1
        message = Message(
            id=message_id or new_ulid(),
            chat_id=chat_id,
            parent_id=parent_id,
            role=role,
            content=content,
            reasoning=None,
            status=status,
            model_ref=model_ref,
            depth=depth,
            tokens_in=None,
            tokens_out=None,
            cost_micros=None,
            timings=None,
            error=None,
            meta=None,
            created_at=now_ms(),
        )
        self._session.add(message)
        return message

    async def _depth_of(self, message_id: str) -> int:
        """Return the stored depth of a message."""
        stmt = select(Message.depth).where(Message.id == message_id).limit(1)
        depth = (await self._session.execute(stmt)).scalar_one_or_none()
        return int(depth or 0)

    async def set_active_leaf(self, chat_id: str, message_id: str, *, bump: int = 0) -> None:
        """Point a conversation at a new branch tip and mark it updated."""
        await self._session.execute(
            update(Chat)
            .where(Chat.id == chat_id)
            .values(
                active_leaf_id=message_id,
                updated_at=now_ms(),
                message_count=Chat.message_count + bump,
            )
        )

    async def load_active_path(
        self, chat_id: str, *, leaf_id: str | None = None
    ) -> list[MessageNode]:
        """Load the messages on the conversation's current branch.

        One range scan fetches every node of the chat with explicit columns; the branch
        is then walked from the leaf to the root in memory. This is intentionally not a
        recursive SQL query: for the sizes involved, one sequential index scan plus a
        dictionary walk beats a recursive CTE on both dialects, and it produces the
        sibling counts the UI needs in the same pass.

        Args:
            chat_id: Conversation to load.
            leaf_id: Branch tip. Defaults to the chat's ``active_leaf_id``; when that
                is unset, the deepest node wins, which is the natural tip of a
                conversation that has never been branched.

        Returns:
            The path from root to leaf, in order.
        """
        if leaf_id is None:
            leaf_id = (
                await self._session.execute(
                    select(Chat.active_leaf_id).where(Chat.id == chat_id).limit(1)
                )
            ).scalar_one_or_none()

        stmt = (
            select(*_MESSAGE_COLUMNS)
            .where(Message.chat_id == chat_id)
            .order_by(Message.depth, Message.id)
        )
        rows = (await self._session.execute(stmt)).all()
        if not rows:
            return []

        by_id = {row.id: row for row in rows}
        children: dict[str | None, list[str]] = {}
        for row in rows:
            children.setdefault(row.parent_id, []).append(row.id)

        if leaf_id is None or leaf_id not in by_id:
            leaf_id = max(rows, key=lambda row: (row.depth, row.id)).id

        chain: list[str] = []
        cursor: str | None = leaf_id
        seen: set[str] = set()
        while cursor is not None and cursor in by_id and cursor not in seen:
            seen.add(cursor)
            chain.append(cursor)
            cursor = by_id[cursor].parent_id
        chain.reverse()

        path: list[MessageNode] = []
        for message_id in chain:
            row = by_id[message_id]
            siblings = children.get(row.parent_id, [message_id])
            path.append(
                MessageNode(
                    id=row.id,
                    parent_id=row.parent_id,
                    role=row.role,
                    content=row.content,
                    reasoning=row.reasoning,
                    status=row.status,
                    model_ref=row.model_ref,
                    depth=row.depth,
                    tokens_in=row.tokens_in,
                    tokens_out=row.tokens_out,
                    cost_micros=row.cost_micros,
                    timings=row.timings,
                    error=row.error,
                    created_at=row.created_at,
                    sibling_index=siblings.index(message_id),
                    sibling_count=len(siblings),
                )
            )
        return path

    async def soft_delete(self, chat_id: str, *, user_id: str) -> bool:
        """Mark a conversation deleted, keeping it recoverable until it is purged."""
        result = await self._session.execute(
            update(Chat)
            .where(Chat.id == chat_id, Chat.user_id == user_id, Chat.deleted_at.is_(None))
            .values(deleted_at=now_ms(), updated_at=now_ms())
        )
        return bool(cast(CursorResult[Any], result).rowcount)
