"""initial schema

Revision ID: 02331038acbb
Revises:
Create date: 2026-09-11 13:32:45.425111+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import velox_ui.db.types

revision: str = "02331038acbb"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "access_rule",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("subject_kind", sa.String(length=16), nullable=False),
        sa.Column("subject_id", sa.String(length=64), nullable=False),
        sa.Column("object_kind", sa.String(length=16), nullable=False),
        sa.Column("object_id", sa.String(length=255), nullable=False),
        sa.Column("effect", sa.String(length=8), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "subject_kind", "subject_id", "object_kind", "object_id", name="uq_access_rule"
        ),
    )
    op.create_table(
        "app_user",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("email_norm", sa.String(length=320), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("avatar_url", sa.String(length=1024), nullable=True),
        sa.Column("settings", velox_ui.db.types.PackedJson(), nullable=True),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("last_seen_at", sa.BigInteger(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email_norm", name="uq_app_user_email_norm"),
    )
    op.create_table(
        "secret",
        sa.Column("ref", sa.String(length=128), nullable=False),
        sa.Column("nonce", sa.LargeBinary(), nullable=False),
        sa.Column("ciphertext", sa.LargeBinary(), nullable=False),
        sa.Column("hint", sa.String(length=64), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("ref"),
    )
    op.create_table(
        "setting",
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("value", velox_ui.db.types.PackedJson(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "api_key",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("user_id", sa.String(length=26), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("prefix", sa.String(length=16), nullable=False),
        sa.Column("key_hash", sa.String(length=64), nullable=False),
        sa.Column("scopes", velox_ui.db.types.PackedJson(), nullable=True),
        sa.Column("last_used_at", sa.BigInteger(), nullable=True),
        sa.Column("expires_at", sa.BigInteger(), nullable=True),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["app_user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key_hash", name="uq_api_key_hash"),
    )
    with op.batch_alter_table("api_key", schema=None) as batch_op:
        batch_op.create_index("ix_apikey_user", ["user_id"], unique=False)

    op.create_table(
        "folder",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("user_id", sa.String(length=26), nullable=False),
        sa.Column("parent_id", sa.String(length=26), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["parent_id"], ["folder.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["app_user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("folder", schema=None) as batch_op:
        batch_op.create_index("ix_folder_user", ["user_id", "parent_id"], unique=False)

    op.create_table(
        "oidc_identity",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("user_id", sa.String(length=26), nullable=False),
        sa.Column("issuer", sa.String(length=512), nullable=False),
        sa.Column("subject", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["app_user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("issuer", "subject", name="uq_oidc_identity"),
    )
    op.create_table(
        "refresh_token",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("user_id", sa.String(length=26), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("family_id", sa.String(length=26), nullable=False),
        sa.Column("expires_at", sa.BigInteger(), nullable=False),
        sa.Column("revoked_at", sa.BigInteger(), nullable=True),
        sa.Column("user_agent", sa.String(length=512), nullable=True),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["app_user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash", name="uq_refresh_token_hash"),
    )
    with op.batch_alter_table("refresh_token", schema=None) as batch_op:
        batch_op.create_index("ix_refresh_family", ["family_id"], unique=False)
        batch_op.create_index("ix_refresh_user", ["user_id", "expires_at"], unique=False)

    op.create_table(
        "tag",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("user_id", sa.String(length=26), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("color", sa.String(length=16), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["app_user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "name", name="uq_tag_user_name"),
    )
    op.create_table(
        "user_quota",
        sa.Column("user_id", sa.String(length=26), nullable=False),
        sa.Column("requests_per_min", sa.Integer(), nullable=True),
        sa.Column("tokens_per_day", sa.Integer(), nullable=True),
        sa.Column("cost_cents_per_day", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["app_user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "chat",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("user_id", sa.String(length=26), nullable=False),
        sa.Column("folder_id", sa.String(length=26), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("active_leaf_id", sa.String(length=26), nullable=True),
        sa.Column("model_ref", sa.String(length=255), nullable=True),
        sa.Column("pinned", sa.Boolean(), nullable=False),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.Column("message_count", sa.Integer(), nullable=False),
        sa.Column("meta", velox_ui.db.types.PackedJson(), nullable=True),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.Column("deleted_at", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(["folder_id"], ["folder.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["app_user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("chat", schema=None) as batch_op:
        batch_op.create_index("ix_chat_folder", ["user_id", "folder_id"], unique=False)

    op.create_table(
        "chat_tag",
        sa.Column("chat_id", sa.String(length=26), nullable=False),
        sa.Column("tag_id", sa.String(length=26), nullable=False),
        sa.ForeignKeyConstraint(["chat_id"], ["chat.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tag_id"], ["tag.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("chat_id", "tag_id"),
    )
    with op.batch_alter_table("chat_tag", schema=None) as batch_op:
        batch_op.create_index("ix_chat_tag_tag", ["tag_id", "chat_id"], unique=False)

    op.create_table(
        "message",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("chat_id", sa.String(length=26), nullable=False),
        sa.Column("parent_id", sa.String(length=26), nullable=True),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("reasoning", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("model_ref", sa.String(length=255), nullable=True),
        sa.Column("depth", sa.Integer(), nullable=False),
        sa.Column("tokens_in", sa.Integer(), nullable=True),
        sa.Column("tokens_out", sa.Integer(), nullable=True),
        sa.Column("cost_micros", sa.Integer(), nullable=True),
        sa.Column("timings", velox_ui.db.types.PackedJson(), nullable=True),
        sa.Column("error", velox_ui.db.types.PackedJson(), nullable=True),
        sa.Column("meta", velox_ui.db.types.PackedJson(), nullable=True),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["chat_id"], ["chat.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("message", schema=None) as batch_op:
        batch_op.create_index("ix_message_chat", ["chat_id", "depth", "id"], unique=False)
        batch_op.create_index("ix_message_parent", ["chat_id", "parent_id"], unique=False)

    # ### end Alembic commands ###

    # Autogenerate cannot render this one: it is partial and its columns are ordered
    # DESC, and SQLAlchemy cannot reflect expression-based indexes on SQLite. It is
    # written out by hand because the chat list depends on it entirely — without it,
    # the 10 000-conversation listing degrades from an indexed seek to a full scan
    # (ADR-0007). Both dialects accept this exact statement.
    op.execute(
        "CREATE INDEX ix_chat_list ON chat "
        "(user_id, archived, pinned DESC, updated_at DESC, id DESC) "
        "WHERE deleted_at IS NULL"
    )


def downgrade() -> None:
    """Revert the migration."""
    op.execute("DROP INDEX IF EXISTS ix_chat_list")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("message", schema=None) as batch_op:
        batch_op.drop_index("ix_message_parent")
        batch_op.drop_index("ix_message_chat")

    op.drop_table("message")
    with op.batch_alter_table("chat_tag", schema=None) as batch_op:
        batch_op.drop_index("ix_chat_tag_tag")

    op.drop_table("chat_tag")
    with op.batch_alter_table("chat", schema=None) as batch_op:
        batch_op.drop_index("ix_chat_folder")

    op.drop_table("chat")
    op.drop_table("user_quota")
    op.drop_table("tag")
    with op.batch_alter_table("refresh_token", schema=None) as batch_op:
        batch_op.drop_index("ix_refresh_user")
        batch_op.drop_index("ix_refresh_family")

    op.drop_table("refresh_token")
    op.drop_table("oidc_identity")
    with op.batch_alter_table("folder", schema=None) as batch_op:
        batch_op.drop_index("ix_folder_user")

    op.drop_table("folder")
    with op.batch_alter_table("api_key", schema=None) as batch_op:
        batch_op.drop_index("ix_apikey_user")

    op.drop_table("api_key")
    op.drop_table("setting")
    op.drop_table("secret")
    op.drop_table("app_user")
    op.drop_table("access_rule")
    # ### end Alembic commands ###
