"""A fake Ollama server.

It replays Ollama's real wire format rather than an idealised one: newline-delimited
JSON on ``/api/chat``, one object per token, with a final object carrying
``done: true`` and the nanosecond duration counters the adapter reads its metrics
from. If the adapter's parsing is wrong, a contract test against this fails.

Behaviour is steered by the model name so a test can ask for a specific condition
without a configuration handshake:

* ``slow``          — one token per second, the CPU-only host case
* ``oom``           — the out-of-memory error Ollama actually emits
* ``missing``       — the "not found, try pulling it first" error
* ``unloaded``      — absent from ``/api/ps``, so the adapter must announce loading
* ``thinking``      — a reasoning model: text arrives in ``message.thinking`` and
  ``content`` stays empty until the thinking ends, which is what real qwen3 and
  deepseek-r1 responses look like
* ``ghost``         — a model that exists nowhere: ``/api/show``, ``/api/delete`` and
  ``/api/copy`` answer 404, and ``/api/pull`` answers **200** with the error inside
  the stream, exactly as Ollama 0.34 does
* ``slowpull``      — a download that reports progress every 300 ms
* anything else     — a normal, fast generation

Model-management responses were captured from a real Ollama 0.34 host: ``/api/ps``
timestamps carry nanoseconds and a UTC offset, and ``/api/show`` returns its
``parameters`` as padded Modelfile text with repeated ``stop`` keys.

Every management request body is appended to ``app.state.requests`` as
``(path, body)`` so a test can assert what the adapter actually sent.
"""

from __future__ import annotations

import asyncio
import json
from collections.abc import AsyncIterator

from starlette.applications import Starlette
from starlette.requests import Request
from starlette.responses import JSONResponse, StreamingResponse
from starlette.routing import Route

TOKENS = ("Hello", ",", " world", "!", " This", " is", " velox", "-ui", ".")
THINKING_TOKENS = ("Okay", ",", " the", " user", " wants", " a", " greeting", ".")

LOADED_MODELS = ("llama3.2", "slow", "oom", "missing", "thinking")
"""Models `/api/ps` reports as resident. ``unloaded`` is deliberately absent."""


async def _tags(request: Request) -> JSONResponse:
    del request
    return JSONResponse(
        {
            "models": [
                {
                    "name": "llama3.2",
                    "size": 2_019_393_189,
                    "details": {"family": "llama", "quantization_level": "Q4_K_M"},
                },
                {
                    "name": "nomic-embed-text",
                    "size": 274_302_450,
                    "details": {"family": "nomic-bert", "quantization_level": "F16"},
                },
            ]
        }
    )


REQUESTS: list[tuple[str, dict[str, object]]] = []


async def _record(request: Request) -> dict[str, object]:
    body = await request.json()
    REQUESTS.append((request.url.path, body))
    return body


def _not_found(model: object) -> JSONResponse:
    return JSONResponse({"error": f"model '{model}' not found"}, status_code=404)


async def _show(request: Request) -> JSONResponse:
    body = await _record(request)
    if body.get("model") == "ghost":
        return _not_found("ghost")
    return JSONResponse(
        {
            "license": "Apache License 2.0",
            "modelfile": '# Modelfile generated by "ollama show"',
            "parameters": 'stop                           "<|im_start|>"\n'
            'stop                           "<|im_end|>"\n'
            "temperature                    0.6\n"
            "top_k                          20",
            "details": {
                "format": "gguf",
                "family": "llama",
                "parameter_size": "3.2B",
                "quantization_level": "Q4_K_M",
            },
            "model_info": {"llama.context_length": 131072, "llama.embedding_length": 3072},
            "capabilities": ["completion", "tools"],
            "template": "{{ .System }}\n{{ .Prompt }}",
            "modified_at": "2026-09-08T08:41:58.117042021+02:00",
        }
    )


async def _ps(request: Request) -> JSONResponse:
    del request
    return JSONResponse(
        {
            "models": [
                {
                    "name": name,
                    "size": 2_019_393_189,
                    "size_vram": 2_019_393_189,
                    "expires_at": "2026-09-13T11:01:46.726485964+02:00",
                    "context_length": 4096,
                }
                for name in LOADED_MODELS
            ]
        }
    )


def _line(payload: dict[str, object]) -> bytes:
    """Encode one NDJSON line exactly as Ollama does."""
    return json.dumps(payload).encode("utf-8") + b"\n"


async def _chat(request: Request) -> StreamingResponse | JSONResponse:
    body = await _record(request)
    model = str(body.get("model", ""))

    if model == "oom":
        return JSONResponse(
            {
                "error": "model requires more system memory (8.4 GiB) "
                "than is available (3.1 GiB)",
            },
            status_code=500,
        )
    if model == "missing":
        return JSONResponse(
            {"error": 'model "missing" not found, try pulling it first'}, status_code=404
        )

    delay = 1.0 if model == "slow" else 0.0

    async def stream() -> AsyncIterator[bytes]:
        # Ollama's own tool-call shape: the whole call in one chunk, arguments as a
        # JSON object rather than a string, no call id, and `done_reason: "stop"`
        # even though the turn only asked for a tool.
        if model == "tools" and not any(
            message.get("role") == "tool" for message in body.get("messages", [])
        ):
            yield _line(
                {
                    "model": model,
                    "created_at": "2026-09-12T10:00:00.000000Z",
                    "message": {
                        "role": "assistant",
                        "content": "",
                        "tool_calls": [
                            {
                                "function": {
                                    "name": "get_weather",
                                    "arguments": {"city": "Turin"},
                                }
                            }
                        ],
                    },
                    "done": False,
                }
            )
            yield _line(
                {
                    "model": model,
                    "created_at": "2026-09-12T10:00:00.000000Z",
                    "message": {"role": "assistant", "content": ""},
                    "done": True,
                    "done_reason": "stop",
                    "prompt_eval_count": 20,
                    "eval_count": 5,
                    "eval_duration": 500_000_000,
                    "prompt_eval_duration": 100_000_000,
                }
            )
            return
        if model == "thinking":
            for token in THINKING_TOKENS:
                yield _line(
                    {
                        "model": model,
                        "created_at": "2026-09-12T10:00:00.000000Z",
                        # Exactly as real Ollama does it: content empty, thinking set.
                        "message": {"role": "assistant", "content": "", "thinking": token},
                        "done": False,
                    }
                )
        for token in TOKENS:
            if delay:
                await asyncio.sleep(delay)
            yield _line(
                {
                    "model": model,
                    "created_at": "2026-09-12T10:00:00.000000Z",
                    "message": {"role": "assistant", "content": token},
                    "done": False,
                }
            )
        yield _line(
            {
                "model": model,
                "created_at": "2026-09-12T10:00:00.000000Z",
                "message": {"role": "assistant", "content": ""},
                "done_reason": "stop",
                "done": True,
                "total_duration": 1_500_000_000,
                "load_duration": 300_000_000,
                "prompt_eval_count": 26,
                "prompt_eval_duration": 200_000_000,
                "eval_count": len(TOKENS),
                "eval_duration": 900_000_000,
            }
        )

    return StreamingResponse(stream(), media_type="application/x-ndjson")


async def _embed(request: Request) -> JSONResponse:
    body = await request.json()
    inputs = body.get("input", [])
    return JSONResponse({"embeddings": [[0.1, 0.2, 0.3] for _ in inputs]})


async def _pull(request: Request) -> StreamingResponse:
    body = await _record(request)
    model = body.get("model")

    async def stream() -> AsyncIterator[bytes]:
        yield _line({"status": "pulling manifest"})
        if model == "ghost":
            # Ollama answers 200 and reports the failure inside the stream.
            yield _line({"error": "pull model manifest: file does not exist"})
            return
        steps = (
            ("sha256:aaaa", 100, 50),
            ("sha256:bbbb", 300, 0),
            ("sha256:aaaa", 100, 100),
            ("sha256:bbbb", 300, 300),
        )
        for index in range(20 if model == "slowpull" else 1):
            for digest, total, completed in steps:
                if model == "slowpull":
                    await asyncio.sleep(0.3)
                yield _line(
                    {
                        "status": f"pulling {digest[7:]}",
                        "digest": digest,
                        "total": total,
                        "completed": min(total, completed + index),
                    }
                )
        yield _line({"status": "verifying sha256 digest"})
        yield _line({"status": "writing manifest"})
        yield _line({"status": "success"})

    return StreamingResponse(stream(), media_type="application/x-ndjson")


async def _create(request: Request) -> StreamingResponse:
    body = await _record(request)

    async def stream() -> AsyncIterator[bytes]:
        if body.get("from") == "ghost":
            yield _line({"error": "model 'ghost' not found"})
            return
        yield _line({"status": "using existing layer sha256:aaaa"})
        yield _line({"status": "writing manifest"})
        yield _line({"status": "success"})

    return StreamingResponse(stream(), media_type="application/x-ndjson")


async def _delete(request: Request) -> JSONResponse:
    body = await _record(request)
    if body.get("model") == "ghost":
        return _not_found("ghost")
    return JSONResponse({})


async def _copy(request: Request) -> JSONResponse:
    body = await _record(request)
    if body.get("source") == "ghost":
        return _not_found("ghost")
    return JSONResponse({})


async def _generate(request: Request) -> JSONResponse:
    body = await _record(request)
    return JSONResponse(
        {"model": body.get("model"), "response": "", "done": True, "done_reason": "unload"}
    )


def create_app() -> Starlette:
    """Build the fake Ollama ASGI application."""
    app = Starlette(
        routes=[
            Route("/api/tags", _tags, methods=["GET"]),
            Route("/api/show", _show, methods=["POST"]),
            Route("/api/ps", _ps, methods=["GET"]),
            Route("/api/chat", _chat, methods=["POST"]),
            Route("/api/embed", _embed, methods=["POST"]),
            Route("/api/pull", _pull, methods=["POST"]),
            Route("/api/delete", _delete, methods=["DELETE"]),
            Route("/api/copy", _copy, methods=["POST"]),
            Route("/api/create", _create, methods=["POST"]),
            Route("/api/generate", _generate, methods=["POST"]),
        ]
    )
    app.state.requests = REQUESTS
    return app
